delay: 10
period: 1
chunks: 100
regions:
  0:
    biomes: [plains]
    weight: 1.0
    plants: [grass, dandelion, poppy, oxeye_daisy, azure_bluet, tulip]
    probabilities: [0.9, 0.0334, 0.0333, 0.0111, 0.0111, 0.0111]
  1:
    biomes: [flower_forest]
    weight: 1.0
    plants: [grass, poppy, allium, azure_bluet, tulip, oxeye_daisy]
    probabilities: [0.112, 0.111, 0.111, 0.111, 0.444, 0.111]
  2:
    biomes: [desert, desert_hills, desert_mountains]
    weight: 0.05
    plants: [dead_bush, cactus, sugar_cane]
    probabilities: [0.333, 0.333, 0.334]
  3:
    biomes: [mesa, mesa_bryce, mesa_plateau, mesa_plateau_mountains]
    weight: 0.05
    plants: [dead_bush, cactus]
    probabilities: [0.5, 0.5] 
  4:
    biomes: [savanna, savanna_plateau, savanna_mountains, savanna_plateau_mountains]
    weight: 1.0
    plants: [grass]
    probabilities: [1.0]
  5:
    biomes: [forest, forest_hills, birch_forest, birch_forest_hills, roofed_forest, birch_forest_mountains, birch_forest_hills_mountains, roofed_forest_mountains]
    weight: 0.5
    plants: [grass, dandelion, poppy]
    probabilities: [0.9, 0.333, 0.667]